CREATE TABLE cidadao.situacao_processo
(
    id        int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    codigo    VARCHAR(80)  NOT NULL,
    descricao VARCHAR(100) NOT NULL,
    ativo     bool         NOT NULL,
    ordem     int4         NOT NULL,
    CONSTRAINT pk_situacao_processo PRIMARY KEY (id),
    CONSTRAINT ux_situacao_processo_codigo UNIQUE (codigo),
    CONSTRAINT ux_situacao_processo_ordem UNIQUE (ordem)
);

COMMENT ON TABLE cidadao.situacao_processo IS 'Entidade responsável por armazenar as situação do processo.';
COMMENT ON COLUMN cidadao.situacao_processo.id IS 'Identificador único da situação do processo.';
COMMENT ON COLUMN cidadao.situacao_processo.codigo IS 'Código da situação do processo.';
COMMENT ON COLUMN cidadao.situacao_processo.descricao IS 'Descrição da situação do processo.';
COMMENT ON COLUMN cidadao.situacao_processo.ativo IS 'Indica se a situação do processo está ativo.';
COMMENT ON COLUMN cidadao.situacao_processo.ordem IS 'Ordem em que a situação do processo deverá ser exibida.';

INSERT INTO cidadao.situacao_processo
    (id, codigo, descricao, ativo, ordem)
VALUES (1, 'EM_CADASTRAMENTO', 'Em Cadastramento', TRUE, 1);

INSERT INTO cidadao.situacao_processo
    (id, codigo, descricao, ativo, ordem)
VALUES (2, 'PENDENTE_UPLOAD_ARQUIVO', 'Aguardando finalização de upload de arquivos', TRUE, 2);

INSERT INTO cidadao.situacao_processo
    (id, codigo, descricao, ativo, ordem)
VALUES (3, 'PENDENTE_VALIDACAO_VINCULO_RT', 'Aguardando validação de vínculo RT', TRUE, 3);

INSERT INTO cidadao.situacao_processo
    (id, codigo, descricao, ativo, ordem)
VALUES (4, 'AGUARDANDO_APROVACAO', 'Aguardando aprovação', TRUE, 4);

INSERT INTO cidadao.situacao_processo
    (id, codigo, descricao, ativo, ordem)
VALUES (5, 'EM_ANALISE', 'Em análise', TRUE, 5);

INSERT INTO cidadao.situacao_processo
    (id, codigo, descricao, ativo, ordem)
VALUES (6, 'APROVADO', 'Aprovado', TRUE, 6);

INSERT INTO cidadao.situacao_processo
    (id, codigo, descricao, ativo, ordem)
VALUES (7, 'REPROVADO', 'Reprovado', TRUE, 7);

INSERT INTO cidadao.situacao_processo
    (id, codigo, descricao, ativo, ordem)
VALUES (8, 'CANCELADO', 'Cancelado', TRUE, 8);