CREATE TABLE cidadao.tipo_uso
(
    id    int8 GENERATED BY DEFAULT AS IDENTITY,
    nome  VARCHAR(100) NOT NULL,
    ativo bool         NOT NULL,
    ordem int4         NOT NULL,
    CONSTRAINT pk_tipo_uso PRIMARY KEY (id)
);

COMMENT ON TABLE cidadao.tipo_uso IS 'Entidade responsável por armazenar os tipo de uso.';

COMMENT ON COLUMN cidadao.tipo_uso.id IS 'Identificador único do tipo de uso.';
COMMENT ON COLUMN cidadao.tipo_uso.nome IS 'Título do tipo de uso.';
COMMENT ON COLUMN cidadao.tipo_uso.ativo IS 'Indica se o tipo de uso está ativo.';
COMMENT ON COLUMN cidadao.tipo_uso.ordem IS 'Formatos aceitos do tipo de uso.';

INSERT INTO cidadao.tipo_uso(nome, ativo, ordem)
VALUES ('Residencial', TRUE, 1);

INSERT INTO cidadao.tipo_uso(nome, ativo, ordem)
VALUES ('Comercial', TRUE, 2);

INSERT INTO cidadao.tipo_uso(nome, ativo, ordem)
VALUES ('Misto', TRUE, 3);

INSERT INTO cidadao.tipo_uso(nome, ativo, ordem)
VALUES ('Industrial', TRUE, 4);
