CREATE TABLE cidadao.informacao_imovel
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY,
    id_tipo_uso int8 NOT NULL,
    id_endereco int8 NOT NULL,
    CONSTRAINT pk_informacao_imovel PRIMARY KEY (id),
    CONSTRAINT fk_informacao_imovel_tipo_uso FOREIGN KEY (id_tipo_uso) REFERENCES cidadao.tipo_uso (id),
    CONSTRAINT fk_informacao_imovel_endereco FOREIGN KEY (id_endereco) REFERENCES dado_global.endereco (id)
);

CREATE INDEX fk_informacao_imovel_idx ON cidadao.informacao_imovel USING btree (id_tipo_uso, id_endereco);

COMMENT ON TABLE cidadao.informacao_imovel IS 'Entidade responsável por armazenar informações do imóvel.';

COMMENT ON COLUMN cidadao.informacao_imovel.id IS 'Identificador único da tabela.';
COMMENT ON COLUMN cidadao.informacao_imovel.id IS 'Identificador do tipo de uso.';
COMMENT ON COLUMN cidadao.informacao_imovel.id IS 'Identificador do endereço.';

COMMENT ON CONSTRAINT fk_informacao_imovel_tipo_uso ON cidadao.informacao_imovel IS 'Chave estrangeira que referencia o tipo de uso.';
COMMENT ON CONSTRAINT fk_informacao_imovel_endereco ON cidadao.informacao_imovel IS 'Chave estrangeira que referencia o endereço.';
