CREATE TABLE cidadao.caracterizacao_imovel
(
    id                int8 GENERATED BY DEFAULT AS IDENTITY,
    setor             varchar(255) NOT NULL,
    quadra            varchar(255) NOT NULL,
    lote              varchar(255) NOT NULL,
    unidade           varchar(255) NULL,
    area_terreno      float        NOT NULL,
    testada_principal float        NOT NULL,
    fracao_ideal      float        NULL,
    data_inclusao     date         NOT NULL,
    CONSTRAINT pk_caracterizacao_imovel PRIMARY KEY (id)
);

COMMENT ON TABLE cidadao.caracterizacao_imovel IS 'Tabela para armazenar a caracterização de imóveis dos cidadãos';

COMMENT ON COLUMN cidadao.caracterizacao_imovel.id IS 'Identificador único do imóvel, gerado automaticamente';
COMMENT ON COLUMN cidadao.caracterizacao_imovel.setor IS 'Setor do imóvel';
COMMENT ON COLUMN cidadao.caracterizacao_imovel.quadra IS 'Quadra do imóvel';
COMMENT ON COLUMN cidadao.caracterizacao_imovel.lote IS 'Lote do imóvel';
COMMENT ON COLUMN cidadao.caracterizacao_imovel.unidade IS 'Unidade adicional do imóvel (opcional)';
COMMENT ON COLUMN cidadao.caracterizacao_imovel.area_terreno IS 'Área do terreno do imóvel';
COMMENT ON COLUMN cidadao.caracterizacao_imovel.testada_principal IS 'Tamanho da testada principal do imóvel';
COMMENT ON COLUMN cidadao.caracterizacao_imovel.fracao_ideal IS 'Fração ideal do imóvel (opcional)';
COMMENT ON COLUMN cidadao.caracterizacao_imovel.data_inclusao IS 'Data de inclusão do registro';