CREATE EXTENSION IF NOT EXISTS "unaccent";
CREATE EXTENSION IF NOT EXISTS "postgis";

CREATE TABLE cidadao.georreferenciamento
(
    id        int8 GENERATED BY DEFAULT AS IDENTITY,
    geometria geometry(geometry, 4674) NOT NULL,
    id_imovel int4                     NOT NULL,
    CONSTRAINT pk_georreferenciamento PRIMARY KEY (id),
    CONSTRAINT fk_imovel FOREIGN KEY (id_imovel) REFERENCES cidadao.imovel ON DELETE CASCADE
);
CREATE INDEX sidx_georreferenciamento_geometria ON cidadao.georreferenciamento USING gist (geometria);

COMMENT ON TABLE cidadao.georreferenciamento IS 'Tabela para armazenar informações de georreferenciamento de imóveis';

COMMENT ON COLUMN cidadao.georreferenciamento.id IS 'Identificador único do georreferenciamento';
COMMENT ON COLUMN cidadao.georreferenciamento.geometria IS 'Geometria associada ao georreferenciamento';
COMMENT ON COLUMN cidadao.georreferenciamento.id_imovel IS 'Chave estrangeira para a tabela imovel';

COMMENT ON CONSTRAINT pk_georreferenciamento ON cidadao.georreferenciamento IS 'Restrição de chave primária para a tabela georreferenciamento';
COMMENT ON CONSTRAINT fk_imovel ON cidadao.georreferenciamento IS 'Chave estrangeira para a tabela imovel, com ação de exclusão em cascata';