CREATE TABLE dado_global.camada_categoria
(
    id        int8 GENERATED BY DEFAULT AS IDENTITY,
    codigo    varchar(255) NOT NULL,
    CONSTRAINT camada_categoria_pk PRIMARY KEY (id)
);

-- Comentário para a tabela
COMMENT ON TABLE dado_global.camada_categoria IS 'Tabela para armazenar categorias de camadas de dados globais.';

-- Comentários para as colunas
COMMENT ON COLUMN dado_global.camada_categoria.id IS 'Identificador único da categoria de camada.';
COMMENT ON COLUMN dado_global.camada_categoria.codigo IS 'Código da categoria de camada.';

-- Comentário para a restrição
COMMENT ON CONSTRAINT camada_categoria_pk ON dado_global.camada_categoria IS 'Restrição para garantir a unicidade do ID da categoria de camada.';

INSERT INTO  dado_global.camada_categoria(codigo) VALUES ('TRECHO_LOGRADOURO');
INSERT INTO  dado_global.camada_categoria(codigo) VALUES ('LOTE');
INSERT INTO  dado_global.camada_categoria(codigo) VALUES ('QUADRA');
INSERT INTO  dado_global.camada_categoria(codigo) VALUES ('SETOR');
INSERT INTO  dado_global.camada_categoria(codigo) VALUES ('LIMITE_MUNICIPAL');
INSERT INTO  dado_global.camada_categoria(codigo) VALUES ('EDIFICACAO');
INSERT INTO  dado_global.camada_categoria(codigo) VALUES ('OUTROS');