CREATE TABLE dado_global.camada
(
    id        int8 GENERATED BY DEFAULT AS IDENTITY,
    nome      varchar(200) NOT NULL,
    codigo    varchar(255) NOT NULL,
    ordem     int4         NULL,
    id_camada_categoria int4 NOT NULL,
    CONSTRAINT camada_pk PRIMARY KEY (id),
    CONSTRAINT fk_camada_categoria FOREIGN KEY (id_camada_categoria) REFERENCES dado_global.camada_categoria (id)
);

-- Comentário para a tabela
COMMENT ON TABLE dado_global.camada IS 'Tabela para armazenar informações de camadas de dados globais.';

-- Comentários para as colunas
COMMENT ON COLUMN dado_global.camada.id IS 'Identificador único da camada.';
COMMENT ON COLUMN dado_global.camada.nome IS 'Nome da camada.';
COMMENT ON COLUMN dado_global.camada.codigo IS 'Código da camada.';
COMMENT ON COLUMN dado_global.camada.ordem IS 'Ordem de prioridade da camada.';
COMMENT ON COLUMN dado_global.camada.id_camada_categoria IS 'Chave estrangeira para a tabela camada_categoria.';

-- Comentário para a restrição
COMMENT ON CONSTRAINT camada_pk ON dado_global.camada IS 'Restrição para garantir a unicidade do ID da camada.';
COMMENT ON CONSTRAINT fk_camada_categoria ON dado_global.camada IS 'Chave estrangeira para a tabela camada_categoria.';
