CREATE TABLE cidadao.notificacao_visualizada (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_notificacao int8 NOT NULL,
    id_usuario UUID NOT NULL,
    data_visualizacao timestamp NOT NULL DEFAULT NOW(),
    CONSTRAINT notificacao_visualizada_pk PRIMARY KEY (id),
    CONSTRAINT notificacao_visualizada_fk FOREIGN KEY (id_notificacao) REFERENCES cidadao.notificacao
);

COMMENT ON TABLE cidadao.notificacao_visualizada IS 'Tabela que registra quando uma notificação foi visualizada por um usuário.';

-- Comentários para as colunas
COMMENT ON COLUMN cidadao.notificacao_visualizada.id IS 'Identificador único para o registro da visualização da notificação.';
COMMENT ON COLUMN cidadao.notificacao_visualizada.id_notificacao IS 'Identificador da notificação visualizada, referenciado na tabela cidadao.notificacao.';
COMMENT ON COLUMN cidadao.notificacao_visualizada.id_usuario IS 'Identificador do usuário que visualizou a notificação.';
COMMENT ON COLUMN cidadao.notificacao_visualizada.data_visualizacao IS 'Data e hora em que a notificação foi visualizada, com valor padrão como a data e hora atuais.';

-- Comentários para as restrições
COMMENT ON CONSTRAINT notificacao_visualizada_pk ON cidadao.notificacao_visualizada IS 'Chave primária da tabela de visualização de notificações.';
COMMENT ON CONSTRAINT notificacao_visualizada_fk ON cidadao.notificacao_visualizada IS 'Chave estrangeira referenciando a notificação na tabela cidadao.notificacao.';