CREATE TABLE dado_global.endereco
(
    id           int8 GENERATED BY DEFAULT AS IDENTITY,
    cep          VARCHAR(10),
    logradouro   VARCHAR(255),
    id_municipio int4 NOT NULL,
    bairro       VARCHAR(100),
    numero       VARCHAR(10),
    complemento  VARCHAR(100),
    CONSTRAINT pk_endereco PRIMARY KEY (id),
    CONSTRAINT fk_endereco_municipio FOREIGN KEY (id_municipio) REFERENCES dado_global.municipio (id)
);
COMMENT ON TABLE dado_global.endereco IS 'Entidade responsável por armazenar os endereços.';

COMMENT ON COLUMN dado_global.endereco.id IS 'Identificador único do endereço.';
COMMENT ON COLUMN dado_global.endereco.cep IS 'CEP do endereço.';
COMMENT ON COLUMN dado_global.endereco.logradouro IS 'Logradouro do endereço.';
COMMENT ON COLUMN dado_global.endereco.id_municipio IS 'Identificador único do município associado ao endereco';
COMMENT ON COLUMN dado_global.endereco.bairro IS 'Bairro do endereço.';
COMMENT ON COLUMN dado_global.endereco.numero IS 'Número da residência do endereço.';
COMMENT ON COLUMN dado_global.endereco.complemento IS 'Complemento do endereço.';

COMMENT ON CONSTRAINT fk_endereco_municipio ON dado_global.endereco IS 'Chave estrangeira que referencia a tabela municipio';