CREATE ROLE vallengeo LOGIN
    ENCRYPTED PASSWORD 'V4LL3NG302023*'
    SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;


CREATE DATABASE vallengeo
    WITH OWNER = vallengeo
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    template template0;

\connect vallengeo;

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS uuid-ossp;
CREATE EXTENSION IF NOT EXISTS unaccent;
set datestyle to DMY;
